articles/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include,re_path
from .import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^$',views.articles_list,name="list"),
    re_path(r'^create/', views.article_create, name="create"),

    path('<slug:slug>/',views.article_detail,name="detail"),

]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):

    title = models.CharField(max_length=100)
    slug = models.SlugField()
    intro = models.TextField(max_length=300)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add= True)
    def __str__(self):
        return self.title
    
#null=False, unique=True

articles/forms.py
from django import forms
from .import models


class Creatinganewarticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','slug','intro','body',]

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from .import forms

from django.http import HttpResponse

# Create your views here.

def articles_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,"articles/article_list.html",{'articles':articles})

def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})
   
def article_create(request):
    if request.method =='POST':
        form = forms.Creatinganewarticle(request.POST)  
        if form.is_valid():
            form.save()
            return redirect('articles:list')      
    form = forms.Creatinganewarticle()
    return render(request,'articles/article_creat.html',{'form':form})

articles/templates/articles/article_creat.html
<div class="creat-article">
    <h2>Creat your article</h2>
    <form class="site-form" action="{% url'articles:create' % }" method="post">
        {% csrf_token %}
        {{form}}
        <input type = "submit" value="Create">
</form>
</div>

articles/templates/articles/article_detail.html
{% block content %}
<a href="{% url 'articles:list'  %}">Home</a>

<div class="article-detail">
    <div class="article">
        <h2>{{article.title}}</h2>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% load static %}


<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel = "stylesheet" href="{%static 'styles.css' %}">
    </head>
    <body>
        <h1>Welcom to my site</h1>
        <h2>Here you can see the list of articles:</h2>
        <nav class="navbar">
            <div class="navbar-brand">

                <a href="{% url 'articles:create'  %}" class="navbar-item"><strong>Write your articles here!</strong></a>
            </div>
        </nav>
        <h1><a href="{% url 'articles:list' %}"><img src="{% static 'download.png'}" /></a></h1>
        <div class="articles">
            {% for article in articles %}
            <div class="article">
                
                <h2>{{article.title}}</h2>
                <p>{{article.intro}}</p>
                <p>{{article.date}}</p>
                <a href="{% url 'articles:detail' article.slug %}">Read more</a>
            </div>
            {% endfor %}
        </div>
    </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8 ">
        <title>Homepage</title>
    </head>
    <body>
        <h1>welcom to my site</h1>
        

    </body>
</html>

